// Tunes the new-words-per-day table (src/lib/scheduler/budget.ts) by simulating a learner
// for 180 days at each daily time, and writes the results to docs/SIMULATION.md.
//
//   npm run simulate
//
// Deterministic: the same code gives the same numbers.

import { writeFileSync } from 'node:fs';
import { simulate, type SimDay, type SimSummary } from '../src/lib/scheduler/simulation';

const DAYS = 180;
const BUDGETS = [5, 10, 15, 20, 30, 45];
const TARGETS = Array.from({ length: 16 }, (_, i) => i + 1);
const SEEDS = [1, 2, 3];
const MAX_CATCH_UP_SHARE = 0.03;
/**
 * Targets whose Use + Owned count is within this share of the best count as equally good.
 * The highest targets squeeze out the last few words by front-loading new words, which
 * makes the number of new words swing from day to day; the smallest near-best target gives
 * steadier days for almost the same result.
 */
const NEAR_BEST = 0.1;

type Averaged = SimSummary & { target: number; days: SimDay[] };

function run(minutes: number, target: number): Averaged {
  const results = SEEDS.map((seed) =>
    simulate({ days: DAYS, minutes, newWordsPerDay: target, seed }),
  );
  const keys = Object.keys(results[0]!.summary) as (keyof SimSummary)[];
  const summary = Object.fromEntries(
    keys.map((k) => [k, results.reduce((sum, r) => sum + r.summary[k], 0) / results.length]),
  ) as unknown as SimSummary;
  return { ...summary, target, days: results[0]!.days };
}

function choose(runs: Averaged[], minutes: number): Averaged {
  const allowed = runs.filter(
    (r) => r.catchUpShare <= MAX_CATCH_UP_SHARE && r.minutesPerStudyDay <= minutes,
  );
  const pool = allowed.length ? allowed : runs;
  const best = Math.max(...pool.map((r) => r.use + r.owned));
  // The smallest target that is as good as the best gives the steadiest days.
  return pool.find((r) => r.use + r.owned >= best * (1 - NEAR_BEST))!;
}

const chosen: Averaged[] = [];
for (const minutes of BUDGETS) {
  const runs: Averaged[] = [];
  let sinceBest = 0;
  let best = -1;
  for (const target of TARGETS) {
    const result = run(minutes, target);
    runs.push(result);
    const score = result.use + result.owned;
    if (score > best) {
      best = score;
      sinceBest = 0;
    } else if (++sinceBest >= 3) {
      break; // more new words stopped helping
    }
  }
  // More time never means a lower target.
  const previous = chosen[chosen.length - 1]?.target ?? 0;
  const pick = choose(runs, minutes);
  const final = pick.target >= previous ? pick : runs.find((r) => r.target === previous)!;
  chosen.push(final);
  console.log(
    `${minutes} min: target ${final.target} -> ${final.newWordsPerStudyDay.toFixed(1)} new/day, ` +
      `${final.reviewsPerStudyDay.toFixed(0)} reviews/day, ${final.minutesPerStudyDay.toFixed(1)} min, ` +
      `Use+Owned ${(final.use + final.owned).toFixed(0)}`,
  );
}

const fmt = (n: number, digits = 1) => n.toFixed(digits);
const rows = chosen.map(
  (r, i) =>
    `| ${BUDGETS[i]} min | ${r.target} | ${fmt(r.newWordsPerStudyDay)} | ${fmt(r.reviewsPerStudyDay, 0)} | ` +
    `${fmt(r.writingPerStudyDay)} | ${fmt(r.minutesPerStudyDay)} | ${fmt(r.started, 0)} | ` +
    `${fmt(r.use + r.owned, 0)} (${fmt(r.owned, 0)} Owned) | ${Math.round(r.retention * 100)}% |`,
);

const fifteen = chosen[BUDGETS.indexOf(15)]!;
const weekRows: string[] = [];
for (let week = 0; week < DAYS / 7; week += 2) {
  const studied = fifteen.days.slice(week * 7, week * 7 + 7).filter((d) => d.studied);
  const avg = (f: (d: SimDay) => number) =>
    studied.length ? studied.reduce((sum, d) => sum + f(d), 0) / studied.length : 0;
  weekRows.push(
    `| ${week + 1} | ${fmt(avg((d) => d.minutes))} | ${fmt(
      avg((d) => d.reviews),
      0,
    )} | ` + `${fmt(avg((d) => d.newWords))} | ${fmt(avg((d) => d.writing))} |`,
  );
}

const doc = `# Scheduler simulation

Generated by \`npm run simulate\` (scripts/simulate.ts). Do not edit by hand: change the code
and run it again.

## What it does

A virtual learner uses the real planner and scheduler for ${DAYS} days at each daily time.
For each time, it tries new-word targets from 1 upwards and picks the one that gets the
most words to **Use or Owned** by day ${DAYS}, without catch-up days (at most
${MAX_CATCH_UP_SHARE * 100}% of days) and without going over the time. When several
targets are within ${NEAR_BEST * 100}% of the best, it picks the smallest, which gives
steadier days. Every number is the average of ${SEEDS.length} runs with different random seeds.

The learner:
- studies on about 85% of days (about six days a week), in the evening
- remembers according to the FSRS memory model, with each word given its own hardness,
  and producing a word harder than recognising it; recall on scheduled reviews comes out
  a little under the 90% target (last column), so the numbers lean cautious. FSRS tuned
  to your own reviews (build session S15) closes that gap.
- answers in 4-9 s (recognition) or 6-14 s (typed production), plus 3 s per item for
  feedback; spends 25-45 s on a new word's page plus its three checks; takes 60-100 s
  per writing task, with 85% of sentences accepted

"Per day" figures are averages over study days in the last 60 days (steady state).

## Results

| Daily time | New-word target | New words/day (actual) | Reviews/day | Writing tasks/day | Minutes/day | Words started by day ${DAYS} | Use + Owned by day ${DAYS} | Recall on reviews |
|---|---|---|---|---|---|---|---|---|
${rows.join('\n')}

The new-word target is the most the planner adds in a day. The actual number is lower on
heavy days, because reviews and writing tasks come first and the session has to fit the
time.

## A typical first six months at 15 minutes a day

Averages over the study days of every other week.

| Week | Minutes | Reviews | New words | Writing tasks |
|---|---|---|---|---|
${weekRows.join('\n')}
`;

writeFileSync(new URL('../docs/SIMULATION.md', import.meta.url), doc);
console.log('\nNEW_WORDS_BY_MINUTES = [');
chosen.forEach((r, i) => console.log(`  [${BUDGETS[i]}, ${r.target}],`));
console.log('];\nWrote docs/SIMULATION.md');
